### ISSUE TITLE
Home: Orientation of Image and Location of Agenda link

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#135]
The image of Metro Headquarters mysteriously changed from horizontal orientation to vertical orientation. Maybe this is what is causing the line "Agenda Get PDF" to appear below the image instead of below the meeting name and address?
The image should be horizontal orientation.
The line "Agenda Get PDF" should be below the meeting details and address.

**Comment by reginafcompton** [comment]
I've updated this, so that the "Get PDF" action link appears below the text, not the image. I've kept the horizontal image, since with the vertical image causes some problems with alignment.
Here's what it would look like with both the "PDF" and "Audio" links available:

<img width="1126" alt="screen shot 2017-05-11 at 3 55 41 pm" src="https://cloud.githubusercontent.com/assets/13078679/25971567/593456ae-3662-11e7-807f-7ffa1c472f0b.png">

**Comment by reginafcompton** [comment]
@shrayshray Does that look right?

**Comment by shrayshray** [comment]
@reginafcompton The links look great! I think the vertical image looks fine, but it does push the "Upcoming Meetings" section below the fold. Is the alignment issue with the horizontal image severe? We'd really like to have at least the header for "Upcoming Meetings" above the fold.

**Comment by reginafcompton** [comment]
Put together an example of each (horizontal vs. vertical). Metro will select their preferred view.

**Comment by reginafcompton** [comment]
@shrayshray Can you clarify what needs to happen to resolve this issue? I think we have the image placement, as desired.

**Comment by reginafcompton** [comment]
@shrayshray Got it! The most recent solution is viewable on the staging site. If this works, then could you close the issue?

**Comment by shrayshray** [comment]
Looks great, thanks!
