### ISSUE TITLE
Event: Cancelled meetings missing "Cancelled" designation 

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#144]
This Planning and Programming Committee meeting has been cancelled for over a week. The meeting listing under "Upcoming Meetings" still does not show a strike-through on the date and designation as "cancelled", and the event page does not either: https://boardagendas.metro.net/event/planning-and-programming-committee-e369c1925760/

**Comment by reginafcompton** [comment]
Add an indication that this meeting has been canceled on the Home page, and on the Event detail page. Also, on the Event detail page, be sure that the link to Legistar is there.

**Comment by reginafcompton** [comment]
@shrayshray The cited event does not exist anymore....

Nonetheless, I updated the cancelled designation, so that it appears on the event detail page:

<img width="1259" alt="screen shot 2017-05-30 at 10 58 18 am" src="https://cloud.githubusercontent.com/assets/13078679/26592690/1bd83720-4527-11e7-949e-efa426487948.png">
