### ISSUE TITLE
Board Reports: Filter by Topic

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#157]
@reginafcompton Can we include the option to filter Board Reports by topic? I saw this on Chicago's Councilmatic site. I believe these topics come from Legistar Indices.
![filterbytopic](https://cloud.githubusercontent.com/assets/28063988/26424242/5e3f83d0-4085-11e7-997d-b5d219854008.png)
![indices](https://cloud.githubusercontent.com/assets/28063988/26424244/60393938-4085-11e7-99cf-0909727b437d.png)

**Comment by reginafcompton** [comment]
@shrayshray 
For Chicago, we generated these topics ourselves, by identifying bills with similar descriptions and consolidating those. 

So, for example, all bills that begin with 'condominium claim', 'denial of condo', 'denials of condo', 'denials condo', 'denied condo', 'condominium refuse' _receive a tag of_ 'Condo Refuse Claim'. (All categories here, if you want to see other examples: https://github.com/datamade/chi-councilmatic/blob/master/chicago/helpers.py.) 

We can certainly do this for Metro, but I would ask that you and Omar collaborate on the conceptual portion of this, first - rather than having DataMade invent these categories for you. 

Does this make sense?

**Comment by shrayshray** [comment]
@reginafcompton We were hoping these could be pulled from Legistar Indexes (second screenshot above). Is that possible?

**Comment by camachoo** [comment]
They are available through the api.

Omar Camacho

________________________________

**Comment by reginafcompton** [comment]
@shrayshray - I implemented this change on the staging site. Take look, and let me know what you think: https://lametro.datamade.us/search/

**Comment by shrayshray** [comment]
@reginafcompton can the text of the topic links reflect to capitalization used in Legistar? e.g., the acronym TAP is capitalized in Legistar, but shows as lower case on the staging site.

**Comment by reginafcompton** [comment]
@shrayshray - yes, I've made that change: https://lametro.datamade.us/search/

**Comment by reginafcompton** [comment]
@shrayshray - I deployed this to production. And looking more closely, I see that the more verbose filters get a little crowded. I am going to clean this up, now, and deploy that change! I'll close this issue, when it  looks nicer.

<img width="386" alt="screen shot 2017-09-28 at 3 52 35 pm" src="https://user-images.githubusercontent.com/13078679/30989953-2d0d779c-a465-11e7-93e3-989c19831ab4.png">
