### ISSUE TITLE
Enhancement: Ability to manually upload Agendas to Councilmatic site

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#205]
Ability to upload Agendas/Items to the Councilmatic site directly when Legistar is down.

**Comment by reginafcompton** [comment]
Additional notes about this issue

**The problem**
At the end of August, Granicus received several reports about partial outages in Legistar and other Granicus services. See [here for a summary](http://status.granicusops.com/incidents/hknntk4pjj43) of the incidents. The underlying cause was a cut fiber line in Chicago.

The Granicus [incident history for Legistar](https://granicus.statuspage.io/history) displays a handful of problems every year, e.g., "Slowness," "Cannot login." Granicus, fortunately, consistently addresses issues in **a matter of hours**. 

Still, some of these issues have the potential to delay processes in Councilmatic, for example: (1) a Metro admin cannot login to Legistar and upload a meeting agenda, or (2) the Councilmatic scrapers fail, if trying to access Legistar during an outage. 

**Possible solution**
Metro Councilmatic includes an option to upload an actual PDF, which builds upon our current solution. An admin could upload _an agenda link_ or an actual document: https://github.com/datamade/la-metro-councilmatic/issues/170 

**Questions to consider and potential risks**
Where will we host uploaded PDFs (e.g., an `uploads` directory at the root of LA Metro)? 
Should we remove uploaded PDFs, once Legistar recovers, to prevent data duplication? 

Uploading documents to Councilmatic comes with some risks. Broadly, it creates another access point for adding data and, in turn, undermines the ideal relationship between Councilmatic and its upstream data sources. We presently have an integrated pipeline, which funnels data from a remote source into the Councilmatic site. With an additional data entry option, the model breaks down, creating more opportunities for points of failure. (Indeed, even with the well-tested agenda upload, we encountered [some unexpected behaviors](https://github.com/datamade/la-metro-councilmatic/issues/189). )

I suggest we think further about the value, necessity, and consequences of this enhancement, before implementation.

@derekeder and @fgregg - do you have additional thoughts on this?

**Comment by shrayshray** [comment]
Omar and I had an extensive discussion about this based on the potential risks outlined above. We're trying to balance: 

1. Concern with the manual upload option causing any compromise to the system integrity, and, in a sense, undermining the nature of Councilmatic's relationship with Legistar. This is clearly articulated and legitimate.
2. Metro's requirement to have in place an approach to ensure business continuity in a worst-case-scenario type situation. So while we don't anticipate using the manual upload feature regularly (i.e., it won't be our knee-jerk reaction to use it if there's a delay on Agendas showing up on Friday night), it's important to have in place in order for us to stay in compliance with business continuty plan requirements.

Based on this requirement, we would indeed like to move forward and develop it.

To answer the questions above:
1. Where to host PDFs - on Metro's Councilmatic server. (Manual upload will happen infrequently, if at all, it should not cause an impact on space/performance).
2. Yes, manually uploaded PDFs should be removed once Legistar recovers, in order to prevent data duplication.

**Comment by reginafcompton** [comment]
Closed by PR #249
