### ISSUE TITLE
Events: Board Meeting listed 2x

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#212]
The Regular Board Meeting scheduled for 11/30 at 9am is listed twice on the events page: https://boardagendas.metro.net/events/
 @reginafcompton  Could you look into this?

**Comment by reginafcompton** [comment]
@shrayshray - thanks for taking note of this. We seem to have two entries for the event in ocd api:

https://ocd.datamade.us/ocd-event/ef33b22d-b166-458f-b254-b81f656ffc09/
https://ocd.datamade.us/ocd-event/1e4383c8-7ec0-45ac-ac0c-988e79955e6a/

We'll figure out how that could have happened.

**Comment by reginafcompton** [comment]
@shrayshray - Metro had two events in the Legistar API at the time of a scrape:

http://webapi.legistar.com/v1/metro/events/1265
http://webapi.legistar.com/v1/metro/events/1259 (now defunct)

We grabbed both of these: since they have different EventIds, they look like different events to the scraper! For now, I'll just remove the duplicate, but we've opened an issue for a longer term solution: https://github.com/opencivicdata/pupa/issues/294
