### ISSUE TITLE
Home: Keep an eye on the "Get PDF" button during current meeting (10/18-10/26)

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#218]
Please check the logic for how long the ''Get Agenda PDF" button displays on the Home page during a meeting. 
I think we had changed the logic for how long the "Listen" button displays. Toward the end of today's meeting, the "Listen" button was up but the 'Get Agenda PDF" button was not.

**Comment by reginafcompton** [comment]
@shrayshray – the logic for displaying the "Get Agenda PDF" is relatively straightforward. If the event has a document, [then the button displays](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templates/partials/meeting_details.html#L18). If not, then the explanatory text displays (i.e., "Agenda will be posted no later...").  

So, if the link did not appear, then you have seen something like this:

<img width="656" alt="screen shot 2017-10-06 at 11 58 12 am" src="https://user-images.githubusercontent.com/13078679/31289485-831eb266-aa8e-11e7-88c2-7f3c79880480.png">


Can you give me more information about what happened? Did you see something like the above, or did the link just disappear?

**Comment by shrayshray** [comment]
@reginafcompton There was no message like above, just the "Get Agenda PDF" link was not available ... like it timed out.

**Comment by reginafcompton** [comment]
@shrayshray - thanks for this note....I am not able to reproduce this error locally: I am mocking the time, so that the home page shows the board meeting in question. Then, I walk through the last fifteen minutes, minute-by-minute. The "Get Agenda PDF" link persists. I also do not see anything in our logs that suggests a timeout.

I suggest we keep an eye on this during the next round of meetings. If the problem happens again, can you take note of the time you notice the error, what browser you see it on, and the visual effect – a screenshot would be great! 

I'll rename the error to indicate that we are watching this, but not making any Councilmatic-side changes, for the time being.

**Comment by reginafcompton** [comment]
@shrayshray - this issue seems to be an anomaly. I have not been able to reproduce it locally, and I have not seen it during meetings, in the last few months. Do you feel comfortable closing?

**Comment by shrayshray** [comment]
@reginafcompton yes,
