### ISSUE TITLE
Events: Remove Solr dependency 

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#233]
Currently, we discover minutes related to a Board Meeting using the Solr search engine: https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templatetags/lametro_extras.py#L101

Let's find a way to do this without using Solr.

**Comment by shrayshray** [comment]
Per Reginia's email 11/9/2017, it's anticipated this will be addressed by the end of January.

**Comment by reginafcompton** [comment]
@shrayshray - this issue does not directly relate to issue #232 (which we'll address by the end of January). Rather, this issue makes a change to the Solr-dependency on the events page.

**Comment by reginafcompton** [comment]
We have a fix for this! PR #424. @hancush will deploy it to production tomorrow and close the issue!

**Comment by hancush** [comment]
update: i'm out of the office today, will deploy this (and #425) on monday!

**Comment by hancush** [comment]
fixed a bug in the implementation of this issue in #429, insodoing also debugged some mysterious behavior in the import in https://github.com/datamade/django-councilmatic/pull/243. 

tested successfully locally, but the aforementioned mysterious behavior ("complete" data imports actually being incomplete) is precluding testing on staging because agenda items for this year's board meetings have not been imported, so the associated minutes are not associated with the events and are not showing up. this will be fixed next week (and will also close #430).

in the meantime, because we've tested successfully locally and the production database is in good shape, i think it is safe to deploy this to production.

**Comment by hancush** [comment]
aaaannnnd, it's deployed! @shrayshray, do things look in order to you? (that is, do board meetings that should have minutes, have minutes?)

**Comment by shrayshray** [comment]
@hancush looks good to me!
