### ISSUE TITLE
Board Reports: Title not showing for some Reports

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#237]
Some Board Reports are missing titles. One example: https://boardagendas.metro.net/board-report/2017-0293/

**Comment by shrayshray** [comment]
A couple others:
https://boardagendas.metro.net/board-report/2017-0234/
https://boardagendas.metro.net/board-report/2017-0129/
https://boardagendas.metro.net/board-report/2017-0061/

**Comment by reginafcompton** [comment]
@shrayshray - We generate the title by looking at the "subject" in the board report text. The reports you've noted are "Minutes," which do not have a "subject."

[**A board report with a subject**](https://boardagendas.metro.net/board-report/2017-0677/)

VS.

[**Minutes without a subject**](https://boardagendas.metro.net/board-report/2017-0234/)

**Comment by reginafcompton** [comment]
Metro will subject headers to minutes.

**Comment by reginafcompton** [comment]
It looks like some Board Reports do not have correct titles, even when the PDF indicates that the text has a "Subject" field. ([Note: we custom generate the title from the subject header](https://github.com/datamade/la-metro-councilmatic/blob/46b5d7b31587b8199645e63912b8279744448740/lametro/utils.py#L7)).

**Example** 
https://boardagendas.metro.net/board-report/2016-0803/

_What's going on?_ This Board Report does not have `plain_text` in the OCD API: https://ocd.datamade.us/ocd-bill/51a10723-1671-4ad6-a88c-fb1fbacca1e4/

(An example of a Board Report with plain_text: https://ocd.datamade.us/ocd-bill/18ee15a0-71ca-4fb1-b91d-3b0e42a2de37)

_Why not?_ Legistar has [three versions of the Board Report text](http://webapi.legistar.com/v1/metro/matters/3596/versions). The [second version has plain text](http://webapi.legistar.com/v1/metro/matters/3596/texts/4431), but we only scrape the most recent version. 

@shrayshray - Metro will need to insure that the most recent version of the Board Report text in the Legistar API has `plain_text`.

**Comment by reginafcompton** [comment]
@shrayshray - checking in about this about this one! 

First, it looks like the more recent meeting minutes have subject headers, e.g., https://boardagendas.metro.net/board-report/2017-0809/ That's great! _Is this going to be the standard Metro practice moving forward?_ 

Second, I noted above that the most recent version of Board Report text in the Legistar API sometimes lacks `plain_text`. We [grab the version with the highest number](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/bills.py#L353) - in other words, if there are [three versions](http://webapi.legistar.com/v1/metro/matters/3596/versions), we assume that version 3 is the most recent. Is this accurate? or does Metro consider another version to be the most recent?

**Comment by shrayshray** [comment]
@reginafcompton 1. We've asked the Board Secretary's office to include subject headers going forward, so hopefully this will continue!
2. The highest version number is the most recent, but it's not necessarily the "current' version of the report, i.e., the version approved to go on the agenda. There is a field in the interface which allows users to toggle between versions, and set the version of their choice as "current" (see screenshot).
![legistar-version](https://user-images.githubusercontent.com/28063988/37845954-5d2458de-2e89-11e8-9e82-f152247e01b0.png)

**Comment by reginafcompton** [comment]
@shrayshray - thanks for this clear explanation. 

We need some time to strategize about solutions. We have one question, though: can we assume that the "current version" (i.e., the version we should scrape) is the one with plain_text? 

For example: the following three texts are for Board Report 2016-0803. Only Version 2 contains plain text. 
[Version 1](http://webapi.legistar.com/v1/metro/matters/3596/texts/4430)
[Version 2](http://webapi.legistar.com/v1/metro/matters/3596/texts/4431) - with plain text = the "current version"!
[Version 3](http://webapi.legistar.com/v1/metro/matters/3596/texts/4432)

Is that pattern consistent? Or can older versions have older plain text?

Either way, we'll need to move this issue to April, since it's more involved than we originally envisioned.

**Comment by shrayshray** [comment]
@reginafcompton for 2016-0803, Version 2 is the current version. I'm not absolutely positive having plain text can be relied upon as the indicator a version is the Current one.
1. In 2016-0803, Version 2 is the only one with plain text?
2. Can you confirm - Since we last communicated about this issue in March, this only potential indicator of Current we know of so far?
3. Would it be helpful if I find additional reports with multiple versions, so plain text = current can be validated?

**Comment by shrayshray** [comment]
@reginafcompton Following up on this:
1. You already confirmed Version 2 of 2016-0803 is the only version with plain text. :) Although, it's also the only version with ANY text.
2. In the Legistar API, 'EventItemVersion' indicates the number of the "current" version. This should be the most reliable indicator of which version has the the Subject.
3. Here are some other reports with multiple versions which are missing the Subject on the site:
2018-0582
2018-0536
2018-0534
2018-0238
2018-0152

**Comment by reginafcompton** [comment]
### Examples

For my own reference, I inspected several of [the board reports listed above](https://github.com/datamade/la-metro-councilmatic/issues/237#issuecomment-441796676) to understand how the `MatterVersion` provides the most current version of the Board Report. (Thanks for digging up those examples @shrayshray !)

**2016-0803**
http://webapi.legistar.com/v1/metro/matters/3596
http://webapi.legistar.com/v1/metro/matters/3596/versions
http://webapi.legistar.com/v1/metro/matters/3596/texts/4431

**2018-0582**
https://webapi.legistar.com/v1/metro/matters/5313
https://webapi.legistar.com/v1/metro/matters/5313/versions
https://webapi.legistar.com/v1/metro/matters/5313/texts/6512

**2018-0536**
https://webapi.legistar.com/v1/metro/matters/5267
https://webapi.legistar.com/v1/metro/matters/5267/versions
https://webapi.legistar.com/v1/metro/matters/5267/texts/6445

**2018-0152**
https://webapi.legistar.com/v1/metro/matters/4884
https://webapi.legistar.com/v1/metro/matters/4884/versions
https://webapi.legistar.com/v1/metro/matters/4884/texts/5984

### Next steps

Modify [the scraper](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/bills.py#L352) to determine the `latest_version` by looking at the `MatterVersion`, rather than calculating it. We might be able to leverage the [`_version_rank`](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/bills.py#L332) function, if not override `text` entirely.

**Comment by reginafcompton** [comment]
I deployed the scraper changes this morning, and I ran the scraper manually for the bills mentioned in [Shelly's comment](https://github.com/datamade/la-metro-councilmatic/issues/237#issuecomment-441796676), like so:

```
pupa update lametro bills matter_ids='3596,5313,5267,4884,5265,4969'
```

The nightly full scrape will catch other bills affected by the original problem.

***

The new bill versions have been ported to the Councilmatic database, and the site shows titles for the bills noted above, e.g., https://boardagendas.metro.net/board-report/2016-0803/

@shrayshray, could you take a look for yourself? If the titles appear as expected, then we can close this issue!

**Comment by shrayshray** [comment]
@reginafcompton looks good!
