### ISSUE TITLE
Board Report: Hyperlinks not showing

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#294]
There seems to be an issue displaying hyperlinked text in reports. I included 3 screenshots below, of Report 2018-0133 in Legistar, embedded in the Councilmatic site, and PDF downloaded via the Councilmatic site. In Legistar and in the downloaded PDF, the text "Metro Government Relations Legislative Matrix" is hyperlinked and link URL displays. But in the embedded PDF, the link and URL are missing. Could you please take a look?

1. Report 2018-0133 in Legistar:
![0boardreport-legistar](https://user-images.githubusercontent.com/28063988/39450749-3d573f56-4c81-11e8-8406-f5d918c62772.PNG)

2. Report 2018-0133 embedded (https://boardagendas.metro.net/board-report/2018-0133/):
![1boardreport-embedded](https://user-images.githubusercontent.com/28063988/39450786-5728c6de-4c81-11e8-9f89-3bd0ec99acdb.PNG)

3. Report 2018-0133 as PDF, downloaded from Councilmatic:
![2boardreport-downloaded](https://user-images.githubusercontent.com/28063988/39450804-67049d08-4c81-11e8-9a81-bae0f838b2c8.PNG)

**Comment by shrayshray** [comment]
Any updates on this?

**Comment by reginafcompton** [comment]
No @shrayshray, but we can prioritize for September/October.

**Comment by hancush** [comment]
this turned out to be an instance of #347. 

i've solved this instance, per https://github.com/datamade/la-metro-councilmatic/issues/347#issuecomment-422044629, so [the bill in question](https://boardagendas.metro.net/board-report/2018-0133/) is displayed as expected.

more broadly, @reginafcompton implemented a solution to prevent this phenomenon when items are updated, but there may be some stale documents hanging around that will never be updated because their corresponding event, bill, etc., won't be updated. let's consider clearing everything from the cache and allowing it to be repopulated over time.

this downside of this approach is the very first person to visit an event or bill page will notice a slightly longer loading time (an extra second or two). the upside is that we can more confidently assure that the most recent version of all documents is displayed on the councilmatic site.

what do you think, @shrayshray?

**Comment by shrayshray** [comment]
@hancush Hyperlinks in Board Reports are now showing up as expected in the embedded PDF! However, nothing happens when the hyperlink is clicked. Can you look into this?
![image](https://user-images.githubusercontent.com/28063988/52675224-f46c5780-2eda-11e9-8ec8-f4676e92713d.png)

**Comment by shrayshray** [comment]
Note, this issue is different from [#379 ](https://github.com/datamade/la-metro-councilmatic/issues/379). #379 is about Legistar generated hyperlinks which link to reports and attachments in Legistar. The issue here is about hyperlinks inserted into the report body by report drafters.

**Comment by reginafcompton** [comment]
## What we know

We use [`viewerjs.org` to enable PDF rendering on Councilmatic.](https://viewerjs.org/instructions/) `viewerjs` parses through PDFs and transforms it into html. It adds links to an `annotationLayer` div. 

For example, a working link looks like this:

<img width="1260" alt="Screen Shot 2019-03-25 at 9 56 51 AM" src="https://user-images.githubusercontent.com/13078679/54925368-8e64ee00-4ee4-11e9-908d-a2c41b01bfbf.png">

Metro has broken links (e.g., https://boardagendas.metro.net/board-report/2018-0771/), which seem to be the result of `viewer.js` not correctly adding them to the `annotationLayer`. The result looks like:

<img width="1272" alt="Screen Shot 2019-03-25 at 9 59 19 AM" src="https://user-images.githubusercontent.com/13078679/54925492-c79d5e00-4ee4-11e9-87dc-1d07d0769661.png">

### Next steps

I am not sure why viewer.js cannot make sense of these particular hyperlinks. I updated Councilmatic to the latest version of viewerjs, and that did not succeed.

So, more research needed!

**Comment by reginafcompton** [comment]
@hancush and I discussed next steps on resolving this issue. 

- [ ] research alternatives the viewerjs
- [ ] determine the characteristics of a functional hyperlink: (1) investigate [a PDF](https://boardagendas.metro.net/event/regular-board-meeting-94b40dbd5d08/) that `viewerjs` can properly parse, and (2) ask Metro about how they create PDFs for board reports vs. event agendas.

**Comment by reginafcompton** [comment]
### Alternatives to viewerjs?

It looks like viewerjs is the standard tool. This [StackOverflow article](https://stackoverflow.com/questions/291813/recommended-way-to-embed-pdf-in-html) conveys the dev community's preference for it and, also, shows the dearth of alternative solutions.

Google Docs has an embeddable PDF viewer. I got the broken hyperlinks working using that solution – but only locally. Is it compatible with CORS? does it work on all browsers?

I also found **Prizmdoc**, which offers [the same functionality as `viewerjs`](https://www.accusoft.com/blog/viewerjs-alternative-viewerjs-vs-prizmdoc/), but also comes with many features not necessary for PDF rendering on Councilmatic. It also comes with [a price tag](https://www.accusoft.com/products/prizmdoc/pricing/).

**Comment by jmithani** [comment]
@shrayshray I'm looking into this. Echoing Regina—could you share how you create PDFs, both for event agendas and board reports? It looks like there are some documented errors in the library we use regarding hyperlinks and which software you export from.

**Comment by jmithani** [comment]
We have determined that the hyperlinks work in most instances except when rendered in the PDF viewer. The links work when downloaded from Legistar's website, upon preview in Metro's Legistar, and upon download.

Next steps: implement the newest version of viewer.js.

(When I download the PDF in Firefox and open in Preview or Firefox, I can't click the link—Omar mentioned that could be a security measure. Will confirm.)

**Comment by shrayshray** [comment]
@jmithani re: how PDFs are created. I believe we went over this on the phone, but just to make sure it's documented - PDFs are generated by Legistar when the Agenda is published to InSite.

**Comment by hancush** [comment]
hm, it looks like `viewer.js` has the same issue as `pdf.js`, which makes sense, since it uses `pdf.js` to render pdfs. https://github.com/webodf/ViewerJS/issues/31

**Comment by hancush** [comment]
i am very intrigued by the `<object>` element! https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

going to spike that out.

**Comment by hancush** [comment]
fyi @shrayshray, i've got a promising start to a resolution going over in https://github.com/datamade/la-metro-councilmatic/pull/489. i'm going to put this down to focus on autocomplete, but once that's launched, this will be ready to go up on staging for you all to test!

**Comment by hancush** [comment]
@shrayshray I've applied my test change to the board report page and deployed the result to the staging site. Can you confirm that hyperlinks are visible and clickable on these pages, which have been problematic in the past?

- https://lametro-upgrade.datamade.us/board-report/2016-0999/
- https://lametro-upgrade.datamade.us/board-report/2018-0133/

N.b., I can click the Metro Government Legislative Matrix links in 2018-0133, but the URL is truncated so it leads to an error page. The same thing occurs when I download the board report, both from Legistar and from the board reports site, and click the link in my local copy, i.e., I think this is a problem inherent to this particular document, not the PDF viewer. The whitehouse.gov link works just fine for me, though!

**Comment by shrayshray** [comment]
@hancush they are working in Chrome! Oddly though, they're not working in Firefox, or in Safari on mobile.

**Comment by hancush** [comment]
@shrayshray We hide inline PDFs on mobile, so I think the latter is expected.

I did a little spelunking and I think I've learned that `pdf.js` is the default PDF viewer for Firefox, and clickable hyperlinks is a longstanding issue with that library: https://github.com/mozilla/pdf.js/issues/3172 (We actually use `pdf.js` now, so moving away from it did partially resolve this issue for Chrome.)

In the past, we've considered migration to another PDF viewing library, Viewer.js, but as it's built on `pdf.js`, [it has the same issue with hyperlinks](https://github.com/webodf/ViewerJS/issues?q=is%3Aissue+is%3Aopen+hyperlink).

So, so far, `<object>` is the most compatible solution, but I will look into one or two other libraries, as it doesn't seem like relying on the PDF viewer built into the user's browser is good enough.

**Comment by hancush** [comment]
Stashing this example of adding additional annotations: https://jsfiddle.net/seikichi/RuDvz/2/

**Comment by hancush** [comment]
Looks like Adobe has a PDF rendering SDK, though it would require per-site credentials, which isn't ideal: https://github.com/adobe/pdf-embed-api-samples

**Comment by hancush** [comment]
Spiked out Adobe – doesn't allow clicking links inline, so off the table.

**Comment by hancush** [comment]
I've spent a couple of hours on this now. The root issue is that `pdf.js` does not automatically create clickable hyperlinks from embedded URLs. `viewer.js`, which we considered migrating to, is built from `pdf.js`, and has the same issue. There is one pretty complex example of manually parsing a PDF and adding clickable polygons to the rendered canvas, but this seems error prone and outside of our area of expertise.

I tried migrating away from `pdf.js` to the `<object>` element, which allows browsers to use their built-in PDF rendering to show the document. This resolves this issue on Chrome, which has [63% of marketshare across all platforms](https://gs.statcounter.com/browser-market-share), but the issue remains on Firefox and Safari. 

I also looked into Adobe's new PDF rendering API, but it does not support clickable inline links.

I am not sure that there is a programmatic solution to this particular issue. 

The core need here is that we want users to be able to navigate to hyperlinks included in PDF documents. One way we can do this is to prompt users to copy/paste embedded URLs into their address bar, or download the file and open it in a program like Preview or Adobe Reader that does support clicking embedded links. 

There may also be a way to resolve this by updating the way hyperlinks are added to board reports before they are converted to PDF. We know there must be some way to include them, because hyperlinks added by Legistar are rendered as clickable, as expected. @shrayshray, how are hyperlinks such as the ones in the example board reports https://github.com/datamade/la-metro-councilmatic/issues/294#issuecomment-740195527 added to the document during the authoring process?

**Comment by shrayshray** [comment]
@hancush The links are added in Microsoft Word. When users create or edit a report in Legistar, Legistar opens Microsoft Word. When they're done editing, they click save, then close the Word doc, and it uploads to the Legistar file. So a hyperlink would be added while in the Word interface, by selecting the desired text and right clicking on it, entering the url, etc.

**Comment by hancush** [comment]
Thanks, @shrayshray, I know we have had this conversation back in another lifetime, so I appreciate your reiterating. Remind me: Are there any examples of board reports with hyperlinks (besides those added by Legistar) that _do_ work in the PDF viewer?

**Comment by shrayshray** [comment]
> We hide inline PDFs on mobile, so I think the latter is expected.
Yes, but I meant when I click to view the PDF.

**Comment by shrayshray** [comment]
@hancush I don't have any examples of reports with hyperlinks that do work in the PDF viewer, but I'm not 100% positive there aren't any. If I can find one, I'll add it here.

**Comment by hancush** [comment]
> Yes, but I meant when I click to view the PDF.

Oh, I see. Unfortunately, that's outside of our control, as the document is opened in the mobile browser's PDF viewer, not a page on the site. (Oddly, the links are working on my iPhone SE running iOS 14.)

**Comment by hancush** [comment]
We'll add some text above the PDF viewer about hyperlinks not working on some browsers. @shrayshray  and @camachoo will send some draft text.

**Comment by hancush** [comment]
@shrayshray Thoughts on text advising users that hyperlinks in the rendered documents may not work?

**Comment by shrayshray** [comment]
"To access hyperlinks, please download the report PDF by clicking "Download Board Report".

**Comment by hancush** [comment]
Hey, @shrayshray, this is live on staging! 

![Screen Shot 2021-01-21 at 10 27 04 AM](https://user-images.githubusercontent.com/12176173/105380179-388e2980-5bd3-11eb-8ce4-d72b576c9f51.png)

Look ok?

**Comment by shrayshray** [comment]
@hancush looks great!

**Comment by hancush** [comment]
@shrayshray Deployed!
