### ISSUE TITLE
BEFORE OCT 12 – pic.datamade.us board report is out of sync with Legistar

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#347]
[Board report 2018-0140](https://boardagendas.metro.net/board-report/2018-0140/) was slated for a meeting during the summer but was postponed. While the link we have on file in the bill documents table [resolves to the correct file in Legistar](https://metro.legistar.com/ViewReport.ashx?M=R&N=TextL5&GID=557&ID=4872&GUID=LATEST&Title=Board+Report), the URL generated by the [`full_text_document_url`](https://github.com/datamade/la-metro-councilmatic/blob/9eb2488d8daed516aa29a82f70d1ed8780e08eaa/lametro/templatetags/lametro_extras.py#L59) template tag [still points to the July version](https://pic.datamade.us/lametro/document/?document_url=https%3A%2F%2Fmetro.legistar.com%2FViewReport.ashx%3FM%3DR%26N%3DTextL5%26GID%3D557%26ID%3D4872%26GUID%3DLATEST%26Title%3DBoard%2BReport&filename=agenda) on pic.datamade.us.

**Comment by hancush** [comment]
Also, to be clear, the correct version of the report comes back when you download the report from the board report and event pages. The _only_ place we are showing the wrong report, is the PDF pane.

**Comment by reginafcompton** [comment]
## Problem

In the OCD and Councilmatic database, the url for a Board Report points to the `latest` version of the pdf ([generated here](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/bills.py#L215)). 

When Councilmatic needs to render a PDF, it [visits `https://pic.datamade.us/lametro/document/`](https://github.com/datamade/property-image-cache/blob/master/app.py#L60), where the property image cache does some work:

* [It instantiates an S3 Key](https://github.com/datamade/property-image-cache/blob/master/app.py#L79), assigns it a `key`, and then, looks for that Key in our `councilmatic-document-cache` S3 bucket. 
* [If PIC does not find an existing entry](https://github.com/datamade/property-image-cache/blob/master/app.py#L89), then it creates a new one. 

_What's the issue?_ We use the Board Report's URL as the key, and this URL remains stable, even when the document that Legistar serves changes. The PIC would not know about such changes, since it already cached an earlier version.

**Comment by hancush** [comment]
@reginafcompton would it be too hamfisted / difficult to connect services, to update the cached image when the bill changes?

**Comment by reginafcompton** [comment]
Write a management command in django-councilmatic that deletes all newly updated bills from the pic.

Research if this is possible via bulk delete: https://boto3.amazonaws.com/v1/documentation/api/latest/index.html

**Comment by shrayshray** [comment]
The logic we discussed for consistent treatment of reports and PDF rendering is to:
1. Check whether "Not Viewable via InSite" is True or False. If True, stop/do not display. If False,
2. Check report type (this step becomes necessary once the archive of pre-2015 board documents and Board Boxes is added to Legistar). If "Board Box", display report and PDF. If False,
3. Check whether the report is on a published agenda. If true, display report and PDF. If false, stop/do not display.

**Comment by reginafcompton** [comment]
@shrayshray - Councilmatic now has [a script](https://github.com/datamade/django-councilmatic/pull/222) that will refresh the document cache, every time a bill or event changes. We'll review this script, merge it, and add it to the data import pipeline early next week. 

For the PDF rendering, I'll add the logic you note – though that seems like its more related to this issue: https://github.com/datamade/la-metro-councilmatic/issues/345. So, I'll keep track of any relevant updates there.

**Comment by reginafcompton** [comment]
@shrayshray - I've added the script for refreshing the document cache to the Metro data pipeline! Closing this issue.
