### ISSUE TITLE
Committee Pages:  Move Chief Executive Office outside members list

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#351]
Metro's Chief Executive Office (currently, Phil Washington), is not a board member. He attends all Board meetings, but he's not an official member; and although he does not vote in committees or regular board meetings, he's also not technically a "non-voting member" (like Shirley Choate, for example). Is it possible to create a separate section on committee pages, either below or to the right of the list of official committee members, for the CEO, based on his "Title" as "Chief Executive Officer" and without his "Committee Role"? And exclude him from the committee member list? 
![image](https://user-images.githubusercontent.com/28063988/45910897-e0a44580-bdc1-11e8-983f-e4d277e060f3.png)

**Comment by reginafcompton** [comment]
Steps to take:

- [ ] for Washington's memberships, change the `role` to "Chief Executive Officer" (accomplished via the scraper)
- [ ] create new table/div with Washington's role, name, and link to detail page

**Comment by reginafcompton** [comment]
@shrayshray - I have a solution ready to go, but before I deploy it to staging, I wanted to ask a couple questions:

(1) the expectation is that the `/committees` page now shows one fewer member, right? 

<img width="820" alt="screen shot 2018-10-09 at 4 05 36 pm" src="https://user-images.githubusercontent.com/13078679/46698705-65be9580-cbdd-11e8-95a5-76d2f204f971.png">

(2) I put the "CEO" subsection directly beneath the members table. What do you think? I'd like to get a photo of Phil Washington, so that it's not so bare. Would that be possible?

<img width="1181" alt="screen shot 2018-10-09 at 4 06 04 pm" src="https://user-images.githubusercontent.com/13078679/46698822-aae2c780-cbdd-11e8-969f-a9b3eef0e939.png">


(3) Would you like to see something different on the `person` detail page for Phil Washington? The table states "Member of," but that might be misleading?

<img width="1258" alt="screen shot 2018-10-09 at 4 10 18 pm" src="https://user-images.githubusercontent.com/13078679/46698934-f9906180-cbdd-11e8-8487-de3522e9bb60.png">

**Comment by shrayshray** [comment]
@reginafcompton 
(1) Yes, exactly. The member count displaying as 7 instead of 6 is what prompted the request for this change.
(2) Great! Looks very good, but I agree it would be better to have a headshot for consistency. Here ya go:
![image](https://user-images.githubusercontent.com/28063988/46701130-91d51900-cbd3-11e8-9144-79fb7a04a314.png)

(3) I agree, both the "Sponsored Board Actions" and "Committees"/"Member of" are misleading. Would it be possible to replace this section with text? 

"Phillip A. Washington was unanimously selected CEO of the Los Angeles County Metropolitan Transportation Authority (LA Metro) by the LA Metro Board of Directors on March 12, 2015.

Metro CEO Phillip A. Washington As LA Metro CEO, Washington manages a total balanced budget of $6.6 billion for FY19, is responsible for overseeing $15+ billion in capital projects, providing oversight of an agency of nearly 11,000 employees and transports 1.4 million boarding passengers daily, riding on a fleet of 2,000 clean-air buses and six rail lines. LA Metro is also the lead transportation planning and programming agency for LA County. As such, it is a major construction agency that oversees bus, rail, highway and other mobility-related building projects – together representing the largest modern public works program in North America. 

[Download the biography for Metro CEO Phillip A. Washington ](http://media.metro.net/board/images/biography-ceo-washington.pdf)"

(4) On the same page, could you remove the "More about Metro appointments" link under the headshot?

**Comment by reginafcompton** [comment]
@shrayshray - it's up on the staging site! Can you let me know how it all looks?

https://lametro.datamade.us/person/phil-washington-2daf84e096e2/
https://lametro.datamade.us/committee/planning-and-programming-committee-40a7385ee8be/

**Comment by shrayshray** [comment]
The Committee pages look great! Just one question -- Carrie Bowen is still showing up in the members list. Is this just because it's the staging site?

And one edit on the Phil Washington page: I left an extra line in the copy I sent you and it should be removed. 
![image](https://user-images.githubusercontent.com/28063988/46758998-1894ff00-cc83-11e8-9fdd-cff386eabe9a.png)
