### ISSUE TITLE
Report: Related Board Reports are out of order

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#355]
Related Board Reports should be listed in descending order by date of last action.
![image](https://user-images.githubusercontent.com/28063988/46702010-70296100-cbd6-11e8-8aa8-c54d0a1cfa9f.png)

**Comment by hancush** [comment]
hm, it looks like our solution [doesn't always work](https://lametro.datamade.us/board-report/2016-0988/).

**Comment by reginafcompton** [comment]
Some thoughts! Having to do with the difference between `last_action_date` and `get_last_action_date`.

#### Django Councilmatic
The `last_action_date` for a Bill originates in [the `import_data` script.](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L2693)

The Bill model also has a [`get_last_action_date` function](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/models.py#L361). At first glance, they seem to do the same thing (so, I would need to look closer to understand why Councilmatic needs both). 

#### Metro customizations
Metro overrides `get_last_action_date` (since some bills do not have histories, i.e., the import script did not create a `last_action_date`). [Here's the body-and-soul of Metro's `get_last_action_date`.]( https://github.com/datamade/la-metro-councilmatic/blob/42a62ae550e15093acda8290c2241a82cd6b6dfb/lametro/utils.py#L43) 

In a few places, we have to find a bill's last action date: when the bill does not have one, then we instead call `get_last_action_date`. Here's an example of where that happens: https://github.com/datamade/la-metro-councilmatic/blob/84d0e9c5c954dcc262bce33fd98a4ac58c2f9501/lametro/templates/partials/tags.html

***

A very simple solution to the open issue might be to [add "...or bill.get_last_action_date..." to the lambda](https://github.com/datamade/la-metro-councilmatic/pull/390/files#diff-803b5091212eac625d7bc1c2dd933c21R89).

I think some the Metro code might merit a refactor, however. @hancush and @jmithani, we can talk about that here or in a fresh PR.

**Comment by jmithani** [comment]
Steps agreed on to refactor this section of the code, from @reginafcompton:
-------
Utility function to eliminate: https://github.com/datamade/la-metro-councilmatic/blob/42a62ae550e15093acda8290c2241a82cd6b6dfb/lametro/utils.py#L43

Function on the bill: https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/models.py#L74

(1) remove the utility function `find_last_action_date` by placing its logic under `get_last_action_date`

(2) in search_indexes.py prep the last_action_date by doing: `last_action_date = obj.get_last_action_date()`

https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/search_indexes.py#L25

(3) Refactor this: https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/templates/partials/tags.html#L2 i.e., eliminate the IF conditional and simply call `result.object.get_last_action_date`

(4) adjust test to not use `find_last_action_date`: https://github.com/datamade/la-metro-councilmatic/blob/master/tests/test_bills.py#L120

**Comment by jmithani** [comment]
@shrayshray pushed a fix for this! Here is the report (or one of them, at least) that wasn't displaying Related Reports correctly: https://boardagendas.metro.net/board-report/2016-0988/. How does it look?

**Comment by shrayshray** [comment]
@jmithani looks great, thank you!!

**Comment by reginafcompton** [comment]
Thanks @jmithani !
