### ISSUE TITLE
Meetings: 11/15/18 Operations meeting showing twice

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#386]
There are two Operations, Safety, and Customer Experience Committee meetings showing on the [events page](https://boardagendas.metro.net/events/) for 11/15/18 at 9am. Could you please removed the one without the agenda?
![image](https://user-images.githubusercontent.com/28063988/50714925-a50b4f80-102f-11e9-8a70-45a065f2b1cb.png)

**Comment by reginafcompton** [comment]
@shrayshray - the duplicate event has been removed. 

I am not sure what caused the duplicate. Here are some things I do know: 
- the duplicate events shared the same API source (http://webapi.legistar.com/v1/metro/events/1495)
- the "incorrect" event was added to the OCD database on November 14, 2018 (but never updated)
- the "correct" event was added to the OCD database on June 20, 2018 (and updated as expected, e.g., with Spanish language media, agenda items, etc.)
- We have not made changes to the Metro scraper since November 2

Our scraper logs do not go back to November 14, so it's hard to diagnose the problem. [I opened an issue to address this.](https://github.com/datamade/scrapers-us-municipal/issues/28)

Let me know if you have questions or additional thoughts/information. Otherwise, we can close this issue, provided https://github.com/datamade/scrapers-us-municipal/issues/28.
