### ISSUE TITLE
Hidden bills and events raise Internal Server Error, rather than Page Not Found

### ISSUE THREAD

**Issue by reginafcompton** [datamade/la-metro-councilmatic#399]
The Metro Councilmatic database includes private bills (marked with "restrict_view=True") and test events. Trying to access one of these entries raises an Internal Server Error. 

[Example of bill](https://sentry.io/datamade/lametro-councilmatic/issues/883897462/?referrer=webhooks_plugin)
[Example of event](https://sentry.io/organizations/datamade/issues/914360896/?project=137567&referrer=alert_email&statsPeriod=14d)

It would be better to handle this more gracefully, i.e., with a Page Not Found (404). 

_I'd classify this as a very low priority issue._

**Comment by hancush** [comment]
I had to fix this issue on another app this morning! The problem was that I put my 404.html and 500.html templates in a directory like templates/app_name/404.html, but I needed to tell Django to look for them there by adding templates/app_name to my TEMPLATES > DIRS setting: https://github.com/confluency/stormstore-app/blob/master/stormstore_app/settings.py#L94

Maybe that's at play here?

**Comment by hancush** [comment]
@fatima3558 Update: I don't think my original comment is the problem, as our 404 page _does_ work sometimes, e.g., #747. Let's deprioritize this, for now, and if it stays in the backlog after our meetings next week, let's pair on getting the app running with DEBUG = False and louder logging so you can test locally!
