### ISSUE TITLE
show related topics on the search results page

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#464]
if search includes topics, show related topics. if search is free text, show potentially related topics. the primary challenge is identifying from a query what topics we should use to query smartlogic for related topics.

**Comment by shrayshray** [comment]
Related to "the primary challenge is identifying from a query what topics we should use to query smartlogic for related topics." -- We don't have a spelling suggestion/correction/ "Did you mean?" type feature for search queries. Does Solr have this type of capability? Being able to use spelling suggestion/correction would potentially help us plan how to address the challenge you mention above. 
We're also going to talk to Steve at Smartlogic about this, but wanted to put it out there and get your thoughts.

**Comment by shrayshray** [comment]
@hancush thank you! We talked about this with Steve from Smartlogic and he had some ideas, too. I believe he was going to reach out to you about it - and maybe we all get together for a quick call next week.

**Comment by hancush** [comment]
@shrayshray it'd be awesome to chat about this together! i'd like to focus on launching the base autocomplete functionality, before we move on to this item. is that ok with you?

**Comment by shrayshray** [comment]
@hancush yes, that makes sense.

**Comment by hancush** [comment]
One question I have for Steve: When I used the concepts endpoint to search for related terms, are filters like source system applied to terms in the `associated` array?

**Comment by hancush** [comment]
Another question: Is there a way to query SES to receive related terms for more than one concept? (The first draft hits the concepts endpoint for each term in the query – not a huge problem, just a place for potential enhancement.)

**Comment by hancush** [comment]
Associated terms (most likely) aren't filtered for source system, but Steve had a great suggestion to throw the associated terms at the subject table and return ones that we have in the database as a proxy. I'll do that!

**Comment by hancush** [comment]
@shrayshray @camachoo The first draft of this is in. I fiddled with displaying them beneath the search bar, but I felt that it took up too much space and moved results much too far down. This was my second thought:

<img width="1552" alt="Screen Shot 2020-06-30 at 12 00 56 PM" src="https://user-images.githubusercontent.com/12176173/86155051-7f96bf00-bac9-11ea-8a7e-0cfe4fc49c02.png">

Thoughts on placement?

I also have a question on behavior: We're using the query text to generate related terms. Right now, clicking on a related term issues a new query search for that term. Does that make sense to you all? Demo (it'll load the next page, my local instance is just slow):

![related_terms](https://user-images.githubusercontent.com/12176173/86155523-224f3d80-baca-11ea-98b5-aea9524976df.gif)

I ask because clicking on the facet filters and topics below each result issues a facet search. I could see how it might get confusing if it's not consistent, but maybe that's a function of putting the related terms next to the facets...

What do you think?

**Comment by hancush** [comment]
Update: This has been deployed to staging, so you can test it out yourselves! https://lametro-upgrade.datamade.us/

**Comment by shrayshray** [comment]
@hancush Placement looks great!
I'm okay with a click on a related term issuing a new search. I agree it could be confusing as it's inconsistent with the behavior of filters, but the utility is supposed to be different ... kind of like expanding the search instead of narrowing it.
Question - related terms are only shown when it's a text query? Would it be possible to show related terms when a concept is selected and used as a query?

**Comment by hancush** [comment]
Hey, @shrayshray – yes, that's doable! I'll give it a whack this morning, stand by.

**Comment by hancush** [comment]
Update: Now pulling related terms for the search query as well as topic-related facets (everything but status and fiscal year): https://lametro-upgrade.datamade.us/search/

**Comment by shrayshray** [comment]
This looks AMAZING! I love it. Something that came up while testing, but might be a separate issue - Once I'm in the results for a related term i click on, when I try to switch to "Tag Search" using the button at the top, I get zero results, even though there are tagged reports on the results page. Example:
1. Search for concept "Los Angeles Union Station"
2. I click on one of the related terms, "Location 109" and get 751 results and I see reports tagged "Location 109" in the results.
3. I click on "Tag Search", and zero results are returned.
4. If i go back to the page with 751 results and click on a "Location 109" tag on a report in the results, I get 7 results. 
![image](https://user-images.githubusercontent.com/28063988/86282281-c4872800-bb93-11ea-9142-d60517870023.png)

**Comment by shrayshray** [comment]
I also just tested this by clearing all filters, searching for concept “Location 109” and once results are returned, clicking “Tag Search” – also returned zero results. So should I open a separate issue for this?

But I guess for this issue, related terms – when I do a fresh search for “Location 109” it returns 1179 results. But clicking on “Location 109” from Related Terms returns only 751 results. Is this expected? I thought they would be the same, since they’re both new searches.

**Comment by hancush** [comment]
Good eyes, @shrayshray! I think I know what's going on with both of these issues... Implementing a patch now.

**Comment by hancush** [comment]
Update: I believe I've squashed both bugs! I followed the steps to reproduce both issues (thank you for including them, @shrayshray!), and things appear to be working to me. Look good to you, too? If so, I can deploy this first thing in the AM. 🎇

**Comment by shrayshray** [comment]
@hancush - Hm, this is tricky. I can't figure out what's going on here, because all looked good to go both before and after I ran into this one weird example, but here's where I again got zero results again using "Tag Search": 
1. I search for "Division 01" and get 685 results,
2. I click "Tag Search" and get 4 results!
3. A related term and tag is "Division 1 Imprvmts(Bos Funded)". When I click on that tag in the filters sidebar, there is 1 report tagged with both "Division 01" and "Division 1 Imprvmts(Bos Funded)". So we know there's at least one tagged "Division 1 Imprvmts(Bos Funded)". 
4. I can switch back to "All" then back to "Tag Search" and I still get that one report in the results.
5. When I click on the related term "Division 1 Imprvmts(Bos Funded)" (or when I type it in the search bar - woohoo!) I get 1,883 results. 
6. But when I click on the "Tag Search" button, I get zero results. :/

This is definitely an anomaly. As I said, "Tag Search" was working for other terms I tested both before and after I ran into an issue with this one. What's also weird is I'm not sure the tagged report is in the search results ... I went through the first 7 pages of results and didn't see it. Any ideas?

**Comment by hancush** [comment]
@shrayshray Bless your testing! This was an issue with search terms containing parentheses. I've pushed a fix, and I'm now seeing the tagged result in all results, and filtering for text/topic results returns the expected number of results for `Division 1 Imprvmts(Bos Funded)`.

**Comment by shrayshray** [comment]
@hancush Awesome! Could there be something similar going on with terms containing quotation marks? It looks like the quotation marks get cleared out when the term is selected from the auto suggestions; tagged results will show but "Tag Search" yields zero results. I encountered this with '"Hot Spots" Program' and 'I-605 Corridor "Hot Spot" (Project)'
Showing tagged results:
![image](https://user-images.githubusercontent.com/28063988/86390837-a4b43a80-bc4d-11ea-97ec-7c82e9247b62.png)

"Tag Search" selected, showing zero results:
![image](https://user-images.githubusercontent.com/28063988/86391215-46d42280-bc4e-11ea-8350-7888c55ca10e.png)

**Comment by hancush** [comment]
@shrayshray Patched! https://lametro-upgrade.datamade.us/search/?q=I-605+Corridor+%22Hot+Spot%22+%28Project%29

Thank you again for your careful eye. :-)

**Comment by shrayshray** [comment]
@hancush looks great to me! Thank you for the quick patch.

**Comment by hancush** [comment]
Absolutely, @shrayshray! Generally, we don't deploy on "Fridays" (our office is closed tomorrow), but I know there was some urgency around landing these SES issues. Shall I go ahead and push to production?

**Comment by hancush** [comment]
Otherwise, this can go live first thing Monday!

**Comment by shrayshray** [comment]
@hancush yes, let's wait until Monday, just to be safe. Enjoy the holiday weekend! 🎆 🎆

**Comment by hancush** [comment]
@shrayshray Likewise!

**Comment by hancush** [comment]
@shrayshray We're live! 💃
