### ISSUE TITLE
intention of event packets, include minutes?

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#507]
After a meeting is held, should an event packet include the minutes? Or should it only include the agenda and board report items, as it does before the minutes are finalized?

**Comment by shrayshray** [comment]
Including the minutes in the event packet after the meeting is a fantastic idea. Two considerations:
1. Presently, minutes are only created for the Regular Board Meeting.
2. The time frame in which minutes are posted after the meeting is inconsistent. For example, they're still not posted for the 10/26/19 meeting. 
If the logic was, if there are minutes then include in packet, this would be a very useful enhancement.

**Comment by shrayshray** [comment]
**Update -** Omar pointed out a couple issues with including minutes with the agenda packet:

1. There would be two sets of minutes in every Regular Board Meeting agenda packet. Minutes from the previous meeting, to be approved + minutes of the current meeting, appended to the packet if we move forward with this enhancement. 
There's potentially a conflict/confusion in having two sets of minutes for Regular Board Meetings, especially because there are none for Committee meetings. 

2. To solve the issue, we could remove the minutes from the previous meeting. This would cause a missing item on the Regular Board Meeting agenda (item #2). 
Removing the minutes "to be approved" from the previous meeting isn't the best resolution to any potential confusion.
Omar and I plan to discuss further tomorrow.

**Comment by shrayshray** [comment]
After discussing, we concluded the agenda packet should only include the agenda and board report items, as it does before the minutes are finalized.

**Comment by fgregg** [comment]
great, thanks!
