### ISSUE TITLE
Deploy to a staging site

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#520]
In order to test and QA the changes to LA Metro and the related repositories, we should set up CD for a staging site. 

As the changes are far ranging, it would be best if it was separate from the existing staging infrastructure. It's also likely that we want to take advantage of the containerization we've already done either by using heroku or docker-compose on an EC2.

**Comment by hancush** [comment]
This is done! https://la-metro-councilmatic-staging.herokuapp.com/

Except, there's no data.

**Comment by hancush** [comment]
We're ready to stage this using our AWS infrastructure. The steps for that are as follows:

- [ ] Spin up a new Metro server
- [ ] Deploy the application to that server, so the database is created and migrated
- [ ] Configure the database to accept remote connections from the OCD server
- [ ] Update the scrapers to scrape into the new database
- [ ] Make any adjustments to the Metro ETL script
- [ ] Bake out event and person identifiers, and `scp` them to the new server
- [ ] Run the identifier migration management command

**Comment by hancush** [comment]
For the record, the new EC2 instance is called `LA Metro Councilmatic - Upgrade`. Forest and I both have shell access, and Postgres has been configured to listen for and accept connections from the OCD database. The configs [live here](https://github.com/datamade/server-la-metro-councilmatic-upgrade).

The legacy Metro-related applications in CodeDeploy and Sentry are called `lametro-councilmatic`. I've created new ones called `la-metro-councilmatic` for consistency with this repository. 

When we're ready to turn off the lights on the legacy deployment, we should:

- [ ] Terminate the `metro-councilmatic` EC2 instance
- [ ] Delete the `lametro-councilmatic` CodeDeploy application
- [ ] Delete the `lametro-councilmatic` and `la-metro-councilmatic-staging` Sentry projects

**Comment by hancush** [comment]
Also, the legacy deployment scripts don't use our zero-downtime strategy. I've adapted them to generate an SSL cert on deployment, however the domain is still hard-coded into a few places:

- The Nginx configuration
- The `settings_deployment.deployment_group.py` file
- The `after_install.sh` script

We'll want to update these to match our desired domains for staging and production when we do the cut over.

I started to migrate the deployment scripts to zero-downtime for maintainability, however [we write manually uploaded agendas to the static directory](https://github.com/datamade/la-metro-councilmatic/blob/9a8c0dd232aac453696281d47d256fcb5d98d0d4/lametro/views.py#L257), which is a subdirectory of the project folder. The deployment scripts move this folder around to preserve it between deployments. There isn't an easy way to replicate this behavior in zero-downtime, because it would take some fancy footwork to identify the directory from the previous deployment. 

At a higher level, we should store user uploads outside of ephemeral project directories, either in a central `media/` directory belonging to the datamade user, or even better, remotely in S3.

Both of the above things felt out of scope at this stage of the project.
