### ISSUE TITLE
QA the upgrade test site

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#525]

**Comment by hancush** [comment]
The test site is now live at https://lametro-upgrade.datamade.us. Now it's time to QA.

General prompts:

- Does existing data appear as expected? Are agendas, packets, and audio links available and correct?
- Does new data appear in a timely manner, as expected? 
- We had to refactor some functionality in the upgrade. Are the following issues addressed on the test site?
    - #508 
    - #509 
- Do maps appear as expected on board member pages? #361.
- Do board reports, events, and people have the same identifiers on the test site as they do on the live site?

More to come.

**Comment by shrayshray** [comment]
Other issues impacted by or contingent to the upgrade:

- #481 List the Chair and Vice Chair first on the list of Board of Directors, followed by other members in alphabetical order. 
"We're adding a centralized way to order board members in the upgrade"

- #462 Metro has defined report types as smartlogic tags, so that a report can be classified as multiple types.
"We'd want to wait on implementation until the changes to topics in our end are made in the upgrade."

- #463 Investigate enriched faceting from Smartlogic tags.
"The way topics are represented in our data is changing in the upgrade, so we will probably want to wait on implementation here until those changes come in."
