### ISSUE TITLE
Board Member: Remove "sponsor" language

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#559]
Early on in this project, we removed "Sponsor" language from other areas of the site because board members and committees don't sponsor items in the way city or other legislative council members do. It's more like Metro staff sponsors items, and Metro Board approves, fails, etc. 
Please remove "sponsor" from Board Member pages:
![image](https://user-images.githubusercontent.com/28063988/75399115-4991c600-58b0-11ea-94ec-841f36bb35c6.png)

**Comment by shrayshray** [comment]
#567 hides this section for now, but "sponsor" language should be removed before re-enabling it.

**Comment by hancush** [comment]
I will check whether we have removed this, and update this thread!

**Comment by hancush** [comment]
The sponsored actions section was removed in #578. Person pages now look like this:

<img width="1376" alt="Screen Shot 2020-07-15 at 2 43 33 PM" src="https://user-images.githubusercontent.com/12176173/87588686-afd58480-c6a9-11ea-9b2e-b8693f44c0ee.png">

**Comment by hancush** [comment]
Hey, @shrayshray, TGIF! I took a shot at removing the sponsorship language. I've revised it to concern acting upon, rather than sponsoring, a board report. Here's what that looks like:

![Screen Shot 2020-10-09 at 4 24 22 PM](https://user-images.githubusercontent.com/12176173/95632828-191c2800-0a4c-11eb-8c04-eb7e2ccc38cc.png)
![Screen Shot 2020-10-09 at 4 24 36 PM](https://user-images.githubusercontent.com/12176173/95632836-1b7e8200-0a4c-11eb-9d52-55dc2a54a828.png)

This change is deployed to the staging site, so you can head to any board member page and play around. Let me know what you think!

**Comment by shrayshray** [comment]
@hancush looks perfect!
