### ISSUE TITLE
Board Report: Incorrect dates in History

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#638]
On [2015-0957](https://boardagendas.metro.net/board-report/2015-0957/), in the "History" section below the PDF, the the dates shown for the meetings are off by one day. 
The Regular Board meeting was on 7/23/15, but shows as 7/22/15, and the Construction Committee was on 7/16/15 but shows as 7/15/15.
![image](https://user-images.githubusercontent.com/28063988/89229650-aea3c300-d596-11ea-87a4-6725d5ff539c.png)

**Comment by hancush** [comment]
Hm, curious! Is this happening for all board reports, or just this one, @shrayshray?

**Comment by shrayshray** [comment]
@hancush It's happening on all reports.

**Comment by hancush** [comment]
Did some spelunking!

The underlying problem is that actions have a date (string) that we cast to date time, which is stored in UTC (midnight on the given date). When we go to display the date time in the template, because we have timezone support enabled, the UTC date time is localized. California is several hours behind UTC, so the date is displayed as the day _before_ the correct date.

Dates for bill actions (and memberships) do not come to us with times, so to me, it seems more appropriate to cast them to dates to avoid this issue. That looks like this: https://github.com/datamade/django-councilmatic/compare/2.5...hcg/dates-to-dates.

Unfortunately, I think this is going to be a bit of an annoying change to make because we do a lot of date time comparisons in the app, so those comparisons are going to need to be updated, if we proceed. With that in mind, I want to sanity check this change with @fgregg, before I go in and start updating all these references.

**Comment by hancush** [comment]
Alternatively, we could use [the `utc` template tag](https://docs.djangoproject.com/en/3.1/topics/i18n/timezones/#utc) when we display the dates. Would still require what I'd guess are a fair few updates, and we'd have to remember to use it when we display dates from bill actions and memberships, but may ultimately be less hairy.

**Comment by hancush** [comment]
Going to move forward with the original idea: Cast date strings to dates, and coerce them to date times only where necessary.

**Comment by hancush** [comment]
@shrayshray Just deployed a patch to address this to the staging site. Looks like action dates for the board report you linked are behaving as expected: https://lametro-upgrade.datamade.us/board-report/2015-0957/. Would you mind helping us spot check action dates for a few other board reports, and let me know if it looks good?

**Comment by shrayshray** [comment]
@hancush spot check checks out - looks great!

**Comment by hancush** [comment]
Thank you, @shrayshray. We're live!
