### ISSUE TITLE
Add Sandoval to the board

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#693]
@shrayshray When his headshot and bio come, drop them here and we can get him added!

**Comment by shrayshray** [comment]
Tim Sandoval's photo and bio are below. his bio might get updated at some point, but it was requested to add this one for now.


![Sandoval Headshot](https://user-images.githubusercontent.com/28063988/110019559-78b9ef00-7cdd-11eb-83d6-a4706eb6d071.JPG)
Tim Sandoval moved to Pomona when he was just nine years old. Even as a child, he knew that a community as richly diverse as Pomona was capable of amazing things. As Pomona High’s class speaker, he defended the character of the school and the surrounding community in an impassioned year-end speech. He attended Montvue Elementary, Emerson Middle School, and Pomona High School before finishing his education at University of California, Riverside. 

After graduating, Tim returned to Pomona to help others in our community to access college as well. He led Pomona Valley Community Development Center’s youth programs, and then taught English at a nearby school. In 2001, Tim became a founding member of Bright Prospect, a mentoring organization that has helped more than two thousand low-income youth become part of the first generation of their family to complete their Bachelor’s degrees. Many of these youth come to share Tim’s passion for Pomona, returning after college to give back to the community. 

Tim has proudly served as Pomona Mayor since 2016 and was recently re-elected in Nov. 2020. As Mayor, he has championed initiatives geared toward breathing new life into the community. This includes reinstatement of Pomona’s annual State of the City Address at the Fox Theater which has become an increasingly popular community celebration – highlighting the City’s accomplishments of the past year and outlining visionary goals for the future of Pomona; Pomona Beautiful clean-ups throughout the City each Tuesday and Saturday morning; and the Mayor’s Gala benefiting the Pomona Public Library.  Tim actively represents Pomona outside of the City’s boundaries, serving on several regional boards, including his positions as the Chair to the Board of Directors for the Metro Gold Line Foothill Extension Construction Authority and the Vice-Chair for the Alameda Corridor East (ACE). His most recent appointment in 2021 to the Metropolitan Transportation Authority (MTA) Board of Directors allows him to represent the San Gabriel Valley’s interests as they pertain to regional public transportation.

**Comment by hancush** [comment]
I'm going to take this one on and document how to do this so it's easier to delegate moving forward.

**Comment by hancush** [comment]
1. Add member to the `VOTING_POSTS` object in the Metro scraper.
2. Remove any board memberships without posts that were created prior to the voting posts addition in step 1:
    ```python
    from lametro.models import Person
    Person.objects.get(family_name='<LAST NAME>').memberships.filter(organization__name='Board of Directors', post__isnull=True).delete()
    ```
3. Add the member's headshot to the repo and update the `MANUAL_HEADSHOTS` object.
4. Add the member's bio to the `MEMBER_BIOS` object.

Example:
- Scraper changes: https://github.com/opencivicdata/scrapers-us-municipal/pull/337/
- Metro changes: https://github.com/datamade/la-metro-councilmatic/pull/686/

**Comment by hancush** [comment]
Done and deployed!
