### ISSUE TITLE
High Priority - Events: Listen Links Missing from 6/24 Regular Board and LA Safe

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#740]
The recordings of the June RBM and LA SAFE meetings are not appearing on boardagendas.metro.net. They were set as “Public” on Thursday, 6/24, and the media IDs were also added to the Legistar Minutes tab on the same day. And the links are showing on metro.legistar.com. Can you please look into why they aren't showing on boardagendas.metro.net? 
![image](https://user-images.githubusercontent.com/28063988/123713043-659cd300-d828-11eb-8498-e06552727076.png)

**Comment by hancush** [comment]
Hi, @shrayshray. Our scrapers have been struggling with new bill types and actions, which has been interfering with full and windowed bill scrapes. We've resolved bill types, but are blocked by one new action: What does "APPROVED UNDER RECONSIDERATION" mean? https://webapi.legistar.com/v1/metro/matters/7717/histories

Please let me know ASAP and I can apply a patch to restore full bill scrapes.

Also, for your reference, these are the actions we currently know how to interpret:

- WITHDRAWN
- APPROVED
- RECOMMENDED FOR APPROVAL
- RECEIVED AND FILED
- RECOMMENDED FOR APPROVAL AS AMENDED
- APPROVED AS AMENDED
- APPROVED THE CONSENT CALENDAR
- APPROVED ON CONSENT CALENDAR
- DISCUSSED
- ADOPTED
- ADOPTED AS AMENDED
- FORWARDED WITHOUT RECOMMENDATION
- CARRIED OVER
- RECEIVED
- REFERRED
- FORWARDED DUE TO ABSENCES AND CONFLICTS
- NO ACTION TAKEN
- FAILED

If we see a new action, the scrape will fail until we define what that action means. Are there any additional actions we should add, in addition to "APPROVED UNDER RECONSIDERATION"? 

Thanks a ton.
