### ISSUE TITLE
Board report scrape: Update action definitions

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-councilmatic#741]
@shrayshray Ported from my mistaken diagnosis in #740

Hi, @shrayshray. Our scrapers have been struggling with new bill types and actions, which has been interfering with full and windowed bill scrapes. We've resolved bill types, but are blocked by one new action: What does "APPROVED UNDER RECONSIDERATION" mean? https://webapi.legistar.com/v1/metro/matters/7717/histories

Please let me know ASAP and I can apply a patch to restore full bill scrapes.

Also, for your reference, these are the actions we currently know how to interpret:

- WITHDRAWN
- APPROVED
- RECOMMENDED FOR APPROVAL
- RECEIVED AND FILED
- RECOMMENDED FOR APPROVAL AS AMENDED
- APPROVED AS AMENDED
- APPROVED THE CONSENT CALENDAR
- APPROVED ON CONSENT CALENDAR
- DISCUSSED
- ADOPTED
- ADOPTED AS AMENDED
- FORWARDED WITHOUT RECOMMENDATION
- CARRIED OVER
- RECEIVED
- REFERRED
- FORWARDED DUE TO ABSENCES AND CONFLICTS
- NO ACTION TAKEN
- FAILED

If we see a new action, the scrape will fail until we define what that action means. Are there any additional actions we should add, in addition to "APPROVED UNDER RECONSIDERATION"? 

Thanks a ton.

**Comment by shrayshray** [comment]
From the Board Secretary's office: "Approved Under Reconsideration was the action for Item 54 (file ID 2021-0331) because the vote had to be taken again.

There was a public commenter who said he could not make his comment at the beginning of the board meeting (Chair Garcetti took all agenda comments at the beginning) so public comment was re-opened for that speaker toward the end of the meeting. Once the public commenter made his comment, Chair Garcetti reopened the vote for Item 54 and it was voted on again. 

As for now, there are no new actions to be added besides Approved Under Reconsideration."

**Comment by hancush** [comment]
Cool, @shrayshray, is it correct to interpret "Approved Under Reconsideration" as a passage/approval, then?

**Comment by shrayshray** [comment]
@hancush yes, correct.

**Comment by hancush** [comment]
@shrayshray Added the new action and deployed! (You can see the new action in, well, action, here: https://boardagendas.metro.net/board-report/2021-0331/)

**Comment by shrayshray** [comment]
@hancush great, thank you!
